<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.hope</groupId>
    <artifactId>springcloud_alibaba</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <modules>
        <module>hope-common</module>
        <module>hope-account</module>
        <module>hope-order</module>
        <module>hope-storage</module>
        <module>hope-frontend</module>
        <module>hope-gateway</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <!-- Project revision -->
        <revision>1.0.1</revision>

        <druid.version>1.1.10</druid.version>
        <mybatis.version>3.0.3</mybatis.version>

        <!-- 微服务版本 -->
        <spring.boot.version>3.2.4</spring.boot.version>
        <spring-cloud.version>2023.0.1</spring-cloud.version>
        <spring-cloud-alibaba.version>2023.0.1.0</spring-cloud-alibaba.version>


        <flatten-maven-plugin.version>1.2.7</flatten-maven-plugin.version>

    </properties>


    <dependencyManagement>
        <dependencies>
            <!-- Spring Boot Starter父依赖 -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- Spring Cloud依赖 -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Spring Cloud Alibaba依赖 -->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>

            <dependency>
                <groupId>org.mybatis.spring.boot</groupId>
                <artifactId>mybatis-spring-boot-starter</artifactId>
                <version>${mybatis.version}</version>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>1.18.42</version>
            </dependency>
        </dependencies>

    </dependencyManagement>

</project>
