server:
  port: 8010

spring:
  application:
    name: hope-storage

  datasource:
    url: jdbc:mysql://localhost:3306/tlmall_storage?useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Xc_cy1234#
  main:
    allow-bean-definition-overriding: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
