server:
  port: 8030
spring:
  application:
    name: hope-order
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:db-common.yml    # 引入公共配置文件
      - nacos:nacos-discovery.yml
      - optional:nacos:sentinel-dashboard.yml
