server:
  port: 8020
spring:
  application:
    name: hope-account
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:db-common.yml    # 引入公共配置文件
      - nacos:nacos-discovery.yml