server:
  port: 8020
spring:
  application:
    name: hope-account
  datasource:
    url: jdbc:mysql://localhost:3306/tlmall_account?useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Xc_cy1234#
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis:
  configuration:
    map-underscore-to-camel-case: true